version: "3"
services:
  reverseproxy:
    build:
      context: ../../udagram-reverse-proxy
    image: luethe007/udagram-reverse-proxy
  backend_user:
    build:
      context: ../../udagram-api-users
    image: luethe007/udagram-api-users
  backend_feed:
    build:
      context: ../../udagram-api-feed
    image: luethe007/udagram-api-feed
  frontend:
    build:
      context: ../../udagram-frontend
    image: luethe007/udagram-frontend